// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWS0ds1TPcvfJqZDvFHmpqkXquzne8pjU',
    appId: '1:189839201542:web:80492ebb39d98ed64f3a87',
    messagingSenderId: '189839201542',
    projectId: 'semsdevop',
    authDomain: 'semsdevop.firebaseapp.com',
    storageBucket: 'semsdevop.appspot.com',
    measurementId: 'G-75FET2GNGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiKA9JCjqxFifGAyrclNtOW0sEM-9CYgM',
    appId: '1:189839201542:android:085dd04217fdf7944f3a87',
    messagingSenderId: '189839201542',
    projectId: 'semsdevop',
    storageBucket: 'semsdevop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEEYeFOpfZu4gtEnpUnVHAmWLUe0kxYGA',
    appId: '1:189839201542:ios:d96ccdc4a5bdeab34f3a87',
    messagingSenderId: '189839201542',
    projectId: 'semsdevop',
    storageBucket: 'semsdevop.appspot.com',
    androidClientId: '189839201542-1pds5u40h60jelf4kov142o1el08jq9a.apps.googleusercontent.com',
    iosClientId: '189839201542-ac7vv32if2g4sgk55m3642aurgkq3ih2.apps.googleusercontent.com',
    iosBundleId: 'com.example.sems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEEYeFOpfZu4gtEnpUnVHAmWLUe0kxYGA',
    appId: '1:189839201542:ios:d96ccdc4a5bdeab34f3a87',
    messagingSenderId: '189839201542',
    projectId: 'semsdevop',
    storageBucket: 'semsdevop.appspot.com',
    androidClientId: '189839201542-1pds5u40h60jelf4kov142o1el08jq9a.apps.googleusercontent.com',
    iosClientId: '189839201542-ac7vv32if2g4sgk55m3642aurgkq3ih2.apps.googleusercontent.com',
    iosBundleId: 'com.example.sems',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgylLpBsG_yw9KjgDd-j3u-j2quMx3VXk',
    appId: '1:189839201542:web:ee00695bc7bc32ab4f3a87',
    messagingSenderId: '189839201542',
    projectId: 'semsdevop',
    authDomain: 'semsdevop.firebaseapp.com',
    storageBucket: 'semsdevop.appspot.com',
    measurementId: 'G-X26YR6L0VC',
  );
}
